USE [master]
GO

/****** Object:  Database [ABCDWH]      ******/
CREATE DATABASE [ABCDWH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ABCDWH', FILENAME = N'D:\MSSQL\Data\ABCDWH.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ABCDWH_log', FILENAME = N'D:\MSSQL\Data\ABCDWH_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

-- Create schema if not exists
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'abc_dwh')
BEGIN
    EXEC('CREATE SCHEMA abc_dwh');
END
GO
